import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Smithproxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          GUI for  <a href="https://smithproxy.org">Smithproxy</a>
        </h1>

        <p className={styles.description}>
          Smithproxy is free, featured and fast TCP/UDP/TLS/SOCKS5 proxy written in
          <code className={styles.code}>C++</code>
        </p>

        <div className={styles.grid}>
          <a href="https://smithproxy.readthedocs.io/en/latest/" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find information about smithproxy.</p>
          </a>

          <a href="https://www.youtube.com/channel/UCb7BciVQp2pdQw9ndueTlvA" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Smithproxy by watching videos.</p>
          </a>

          <a
            href="https://github.com/astibal/smithproxy"
            className={styles.card}
          >
            <h2>Visit project github &rarr;</h2>
            <p>Check the source code yourself nad learn about sister project <code>pplay</code>.</p>
          </a>

          <a
            href="https://hub.docker.com/repository/docker/astibal/smithproxy"
            className={styles.card}
          >
            <h2>Deploy docker image &rarr;</h2>
            <p>
              Instantly check smithproxy yourself - <i>astibal/smithproxy:latest</i>
            </p>
          </a>




          <Link href="/content/proxy/list">
          <a
              className={styles.card}
          >
            <h2>Session list &rarr;</h2>
            <p>
              Check live session list
            </p>
          </a>
          </Link>

          <Link href="/content/status/status">
            <a
                className={styles.card}
            >
              <h2>Status &rarr;</h2>
              <p>
                Status
              </p>
            </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            open-source
          </span>
        </a>
      </footer>
    </div>
  )
}
